# Generated by Django 5.0.1 on 2025-02-07 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreId', models.AutoField(primary_key=True, serialize=False)),
                ('genreName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('kinoId', models.AutoField(primary_key=True, serialize=False)),
                ('kinoNer', models.CharField(max_length=50)),
                ('tailbar', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie_images/')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.genre')),
            ],
        ),
    ]
